_enumCount = 0


def startEnum():
    global _enumCount
    _enumCount = 1
    return _enumCount - 1


def nextEnum():
    global _enumCount
    _enumCount += 1
    return _enumCount - 1


MATCH_STATE_WAITING = 0
MATCH_STATE_RUNNING = 1
MATCH_STATE_ENDED = 2
MATCH_STATE_FORCE_TERM = 3


MATCH_TEAM_NULL = 0
MATCH_TEAM_A = 1
MATCH_TEAM_B = 2
MATCH_TEAM_OBSERVER = 3
MATCH_TEAM_ADMIN = 256


MATCH_MAX_TEAM_COUNT = 2
MATCH_MAX_USER_COUNT = 8

MATCH_PLAYER_HUMAN = 1
MATCH_PLAYER_AI = 2

COMPONENT_MANAGER_INIT_SIZE = 0


USE_SPATIAL_HASH = False
CALCULATE_VISIBILITY = True
SPATIAL_HASH_BUCKET_SIZE = 5


COMP_STATUS_RESERVED = 0x0001
COMP_STATUS_ATTACHED = 0x0002
COMP_STATUS_ACTIVE = 0x0004
COMP_STATUS_AWAKE = 0x0008


COMP_MASK_NULL = 0x0000
COMP_MASK_RESERVED = COMP_STATUS_RESERVED
COMP_MASK_ATTACHED = COMP_STATUS_RESERVED | COMP_STATUS_ATTACHED
COMP_MASK_ACTIVE = COMP_STATUS_RESERVED | COMP_STATUS_ATTACHED | COMP_STATUS_ACTIVE
COMP_MASK_AWAKE = COMP_STATUS_RESERVED | COMP_STATUS_ATTACHED | COMP_STATUS_ACTIVE | COMP_STATUS_AWAKE


COMP_TYPE_TRANSFORM = 0
COMP_TYPE_PHYSICAL = 1
COMP_TYPE_SENSOR = 2
COMP_TYPE_ATTRIBUTES = 3
COMP_TYPE_TAGS = 4
COMP_TYPE_COMBATATTRIBUTES = 5
COMP_TYPE_MOVER = 6
COMP_TYPE_WAYPOINTMOVER = 7
COMP_TYPE_EFFECT = 8
COMP_TYPE_PROCESS = 9
COMP_TYPE_FSM = 10
COMP_TYPE_EVENTIO = 11
COMP_TYPE_TIMER = 12
COMP_TYPE_PREDICATE = 13
COMP_TYPE_NETWORK = 14


COMP_EVENT_ATTRIBUTES_CHANGED = startEnum()
COMP_EVENT_USERLOCAL_ATTRIBUTES_CHANGED = startEnum()
COMP_EVENT_COMBATATTRIBUTE_ADDED = nextEnum()
COMP_EVENT_COMBATATTRIBUTE_REMOVED = nextEnum()
COMP_EVENT_TAG_ADDED = nextEnum()
COMP_EVENT_TAG_REMOVED = nextEnum()
COMP_EVENT_MOVEMENT_STARTED = nextEnum()
COMP_EVENT_MOVEMENT_SPEED = nextEnum()
COMP_EVENT_MOVEMENT_DIRECTION = nextEnum()
COMP_EVENT_MOVEMENT_ENDED = nextEnum()
COMP_EVENT_MOVEMENT_TELEPORT = nextEnum()
COMP_EVENT_PATH_STARTED = nextEnum()
COMP_EVENT_PATH_ENDED = nextEnum()
COMP_EVENT_PROCESS_STARTED = nextEnum()
COMP_EVENT_PROCESS_ENDED = nextEnum()
COMP_EVENT_EFFECT_LAUNCHED = nextEnum()
COMP_EVENT_TIMER_TRIGGERED = nextEnum()
COMP_EVENT_EVENT_SENT = nextEnum()
COMP_EVENT_EVENT_RECEIVED = nextEnum()
COMP_EVENT_EVENT_PROCESSED = nextEnum()
COMP_EVENT_COUNT = nextEnum()


WORLD_EVENT_ENTITY_CREATE = startEnum() + COMP_EVENT_COUNT
WORLD_EVENT_ENTITY_DESTROY = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_ENTITY_DEATH = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_ENTITY_SELL = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_ENTITY_RESPAWN = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_DAMAGE = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_HEAL_RECEIVED = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_ATTACK = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_CHARGE = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_TIMED_CHARGE = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_LEAP = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_BUFF = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_HEAL_PERFORMED = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_COUNT = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_BUILDING = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_BUILDING_READY = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_BUILDING_UPGRADING = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_BUILDING_UPGRADED = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_REACH_BASE = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_START_WAVE = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_PLAYER_READY = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_TEAM_ELIMINATED = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_END_GAME_WITH_WINNER = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_LAST_HIT = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_STUN = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_ITEM_PICKUP = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_SCOPE = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_CAST_STARTED = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_CAST_SUCCESS = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_CAST_CANCELED = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_ABILITY_USED = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_ABILITY_ENDED = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_PROC = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_BUFF_EXPIRED = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_AOE_HEAL_PERFORMED = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_AOE_DAMAGE_PERFORMED = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_TUTORIAL_MESSAGE = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_TUTORIAL_UI = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_TUTORIAL_END = nextEnum() + COMP_EVENT_COUNT
WORLD_EVENT_TELEPORT = nextEnum() + COMP_EVENT_COUNT


EVENT_COUNT = COMP_EVENT_COUNT + WORLD_EVENT_COUNT


EPSILON_VECTOR_DISTANCE = .00000001


NULL_ID = -1


ATTR_SET = 0
ATTR_SET_MULTIPLE = 1
ATTR_INC = 2
ATTR_MUL = 3
ATTR_TOGGLE = 4
ATTR_REMOVE = 5


MOD_TYPE_SET = startEnum()
MOD_TYPE_ADD = nextEnum()
MOD_TYPE_MUL = nextEnum()
MOD_TYPE_SET_OVERRIDE = nextEnum()
MOD_TYPE_COUNT = nextEnum()


SHAPE_TYPE_POINT = 0
SHAPE_TYPE_CIRCLE = 1
SHAPE_TYPE_AABB = 2


PHYS_SHAPE = 0
PHYS_CENTER = 1
PHYS_CIRCLE_RADIUS = 2
PHYS_AABB_WIDTH = 2
PHYS_AABB_HEIGHT = 3


SENSOR_SHAPE = 0
SENSOR_NAME = 1
SENSOR_CENTER = 2
SENSOR_CIRCLE_RADIUS = 3
SENSOR_AABB_WIDTH = 3
SENSOR_AABB_HEIGHT = 4


EFFECT_NAME = 0
EFFECT_FUNCTION = 1


PROC_NAME = 0
PROC_FUNCTION = 1
PROC_PERIOD_COUNTER = 2
PROC_PERIOD = 3
PROC_STATUS = 4
PROC_TICK_COUNT = 5


PROC_STATUS_NULL = 0x00
PROC_STATUS_PAUSED = 0x01
PROC_STATUS_TERMINATED = 0x02


PRED_NAME = 0
PRED_EVENT = 1
PRED_TRIGGER_COUNT = 2
PRED_TRIGGER_LIMIT = 3
PRED_CURRENT_COUNTDOWN = 4
PRED_PERIOD = 5
PRED_FUNCTION = 6
PRED_DATA = 7


PRED_INFINITE = -1
PRED_ONCE = 1


TIMER_NAME = 0
TIMER_EVENT = 1
TIMER_TRIGGER_COUNT = 2
TIMER_TRIGGER_LIMIT = 3
TIMER_CURRENT_COUNTDOWN = 4
TIMER_COUNTDOWN_START = 5
TIMER_STATUS = 6
TIMER_DATA = 7


TIMER_STATUS_NULL = 0x00
TIMER_STATUS_TRIGGERED = 0x01
TIMER_STATUS_PAUSED = 0x02
TIMER_STATUS_REMOVED = 0x04


TIMER_INFINITE = -1
TIMER_ONCE = 1


TILE_UNKNOWN = 0
TILE_GRASS = 1
TILE_ROAD = 2
TILE_FOREST = 3
TILE_SHALLOW_WATER = 4
TILE_DEEP_WATER = 5
TILE_START_TEAM_A = 6
TILE_START_TEAM_B = 7
TILE_IND_SLOT_A = 8
TILE_IND_SLOT_B = 9
TILE_DEV_SLOT_A = 10
TILE_DEV_SLOT_B = 11
TILE_WAR_SLOT_A = 12
TILE_WAR_SLOT_B = 13
TILE_IND_SLOT = 14
TILE_DEV_SLOT = 15
TILE_WAR_SLOT = 16


TILE_COUNT = 17


COMPSYS_TYPE_TRANSFORM = 0
COMPSYS_TYPE_MOVER = 1
COMPSYS_TYPE_WAYPOINTMOVER = 2
COMPSYS_TYPE_TIMER = 3
COMPSYS_TYPE_EVENTIO = 4
COMPSYS_TYPE_FSM = 5
COMPSYS_TYPE_PROCESS = 6
COMPSYS_TYPE_PHYSICAL = 7
COMPSYS_TYPE_NETWORK = 8
COMPSYS_TYPE_DEATH = 9
COMPSYS_TYPE_VISIBILITY = 10
COMPSYS_TYPE_PREDICATE = 11


MOVER_SYSTEM_UPDATE_PERIOD = 3
WAYPOINTMOVER_SYSTEM_UPDATE_PERIOD = 3
TIMER_SYSTEM_UPDATE_PERIOD = 4
FSM_SYSTEM_UPDATE_PERIOD = 2
EVENT_SYSTEM_UPDATE_PERIOD = 2
NETWORK_COMMAND_PROCESS_PERIOD = 1
DEATH_CLEANUP_PERIOD = 2
VISIBILITY_UPDATE_PERIOD = 10
PREDICATE_SYSTEM_UPDATE_PERIOD = 10


NODE_ID = 0
NODE_DATA = 1


GRIDNODE_DATA = 0
GRIDNODE_X = 1
GRIDNODE_Y = 2
GRIDNODE_DATA_NODETYPE = 0
GRIDNODE_DATA_HEIGHT = 1


PONG = 0
AUTH = 1
JOIN_REQ = 2
REQ = 3
E_CREAT_REQ = 4
E_DESTR_REQ = 5
E_ATTR_GET_REQ = 6
E_ATTR_SET_REQ = 7
E_MOV_REQ = 8
E_ACT_REQ = 9
E_STOP_REQ = 10
READY_REQ = 11
SURR_REQ = 12


PROP_ROAD_CROSS = 0
PROP_ROAD_NS = 1
PROP_ROAD_EW = 2
PROP_ROAD_NE = 3
PROP_ROAD_NW = 4
PROP_ROAD_SE = 5
PROP_ROAD_SW = 6
PROP_ROAD_TN = 7
PROP_ROAD_TS = 8
PROP_ROAD_TE = 9
PROP_ROAD_TW = 10
PROP_FOREST_3X3 = 11